export default {
    'base':'http://127.0.0.1/loan/back/public',
    // 'base':'http://back.poolak.salam-raya.ir',
    // 'base':'http://poolak.salam-raya.ir/backend',
    // 'base':'http://salam-raya.ir',
    'edit_profile':'api/profile/editProfile',
    'change_password':'api/profile/changePassword',
    'register':'api/auth/register/register',
    'mobile':'api/auth/register/mobile',
    'confirm_code':'api/auth/register/confirm_code',
    'check token':'api/auth/check_token',
    'login':'api/auth/login',
    'pardakht_request':'api/auth/pardakht/request',
    'pardakht_verification':'api/auth/pardakht/verification',
    'loan_groups_index':'api/loan_groups',
    'add_loan_group':'api/loan_groups/add',
    'delete_loan_group':'api/loan_groups/delete',
    'loanGroup':'api/loan_groups/group',
    'loan_group_member':'api/loan_groups/member',
    'add_member_group':'api/loan_groups/member/add',
    'delete_member_group':'api/loan_groups/member/delete',
    'checkout_member':'api/loan_groups/member/checkout',
    'roles':'api/roles',
    'loans':'api/loan_groups/loan',
    'add_loan':'api/loan_groups/loan/add',
    'delete_loan':'api/loan_groups/loan/delete',
    'terminate_loan':'api/loan_groups/loan/terminate',
    'transactions':'api/loan_groups/transaction',
    'add_transaction':'api/loan_groups/transaction/add',
    'delete_transaction':'api/loan_groups/transaction/delete',
    'payments':'api/loan_groups/payments',
    'add_payment':'api/loan_groups/payment/add',
    'delete_payment':'api/loan_groups/payment/delete',
}

